First app
abdul-mohsen/GeoQuiz pull request #1
Opened 2020-10-13 06:37 UTC by abdul-mohsen

completed the listing problem seamlessly with no problem. 

Right now the code just pop up a toast with message when the true or the false button being clicked.

2020-10-13 08:30 UTC, abdul-mohsen commented
forgot to create another branch for the chapter 2 and it is now here

2020-10-14 00:42 UTC, dgreenhalgh requested changes
Great job with your code, but you have some merge conflicts that must be resolved before merging this pull request.

2020-10-14 05:58 UTC, abdul-mohsen commented
I will check. But I did make a bug and I did not notice it until now (The two button true&false return true) and it is in all branches. I tried to fix it using git merge but it got worst because of the reverted commit. And now I have headache & no idea what going on :(( . So for the rest branches I decided to fix it by hand. Idk if there was a better solution for this mess XD

2020-10-14 06:01 UTC, abdul-mohsen commented on app/src/main/java/com/example/geoquiz/MainActivity.kt
> +            checkAnswer(true)
you can see it here

2020-10-15 00:43 UTC, dgreenhalgh commented on app/src/main/java/com/example/geoquiz/MainActivity.kt
> +            checkAnswer(true)
Ah, I see. Thanks for fixing this in future branches!

2020-10-15 00:46 UTC, dgreenhalgh commented
I see that you have some merge conflicts on future branches, so I'll merge this to make those easier 😉

2020-10-15 04:21 UTC, merged